### PR TITLE
Add borg-gtk

### PR DESCRIPTION
**Pull request by Abogical**
This is a project I was working on since last march. A GTK+ frontend for borg. Unfortunately, since this was created before the JSON API, it doesn't use it. So I'm discontinuing this project.

This would be helpful to share here for two reasons:
- Would probably be useful for those trying to also create a frontend.
- There are added features to borg that may be interesting to the main borg project. Check out the repo to know more. It'll be appreciated if you also read `Wishlist.md` to know more about those features that I wish were available in borg when creating a frontend.

Thank you.

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
@Abogical if it is discontinued, you should tell so (link and also README in your repo).

And maybe it shouldn't be placed in between released / production ready projects.

Maybe we could have a "development" section there?

**Comment by Abogical** [comment]
Done.

**Comment by ThomasWaldmann** [comment]
ok, please collapse the changeset, I'll merge it afterwards.

**Comment by Abogical** [comment]
Done.

**Comment by enkore** [comment]
Interesting project

Re. wishlist.md, well, you already saw yourself why borg doesn't do a progress bar (complex / inaccurate / racier). Maybe it's less "intrusive" to extrapolate progress from previous backups? Doesn't solve initial transfers -> maybe something equivalent to (or even just calling) `du(1)` on the tree (but then again issues with excludes etc...)

**Comment by Abogical** [comment]
Also, if `archive.add_item()` was atomic, We can add more 'Workers', minimizing the delay.

**Pull request merged**
