### PR TITLE
Update link to improved borgbench implementation

### PR DESCRIPTION
**Pull request by n-st**
Details at https://github.com/dragetd/borgbench/issues/3

### CODE REVIEW

**Comment by rugk** [comment]
Why did you disable issues for your project?


----
Also if you really want to maintain it, you can detach it from upstream:

You can this either [do it manually](https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub#ld_fjxjzo_52503) **or** – which I recommend – just contact the GitHub support to do it for you.

This…
1. shows that this is a real maintained project and not just a repo of someone who (once) made a pull request
2. linking to the original repo on every page does not make sense anymore as it has been discontinued/is not maintained anymore and you…
3. can (and IMHO should) still link to the original repo/website/author/… for crediting them, but you can do so in better ways (in the Readme, wiki or so)
4. allows searching in this repo on GitHub and
5. it just looks much nicer

**Comment by ThomasWaldmann** [comment]
@dragetd see above. shall we change the link / who maintains this code?

**Comment by n-st** [comment]
@rugk The benchmark tool is just a one-off helper script and was already feature-complete in @dragetd's version. I only cleaned up the code to make it easier to use and potentially modify. The concept and example measurements are still @dragetd's, so I would like to keep the fork relationship intact, while pointing the `borgbackup/community` link to the new repo so borg users get both @dragetd's data and my usability improvements (e.g. paths as commandline arguments instead of hardcoded into the script).

I didn't explicitly change any of the repo settings; not sure why the fork was created with the issue tracker disabled but wiki and project management enabled… Either way, that's fixed now.

**Comment by rugk** [comment]
I think you do it in a strange way. What you actually wanted to do is probably send a PR to the original author.
Because when the author still maintains the code, why did you create such a fork?

So either the author merges you changes and we leave the link here, or you say you'll maintain that script and we can change the link. In the latter you can of course detach the repo and credit the author in another way (prominent link in Readme). I already listed the reasons.

**Comment by dragetd** [comment]
No, everything is alright. My version was just a quick hack. Replace it with his version! =D

**Comment by ThomasWaldmann** [comment]
OK, thanks everybody for improvements and clarification.

**Pull request merged**
